# Generated by Django 5.1.4 on 2025-03-13 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_medicinelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinelog',
            name='date',
        ),
        migrations.AddField(
            model_name='medicinelog',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicinelog',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='status',
            field=models.CharField(choices=[('taken', 'Taken'), ('missed', 'Missed')], default='missed', max_length=10),
        ),
    ]
