# Generated by Django 5.1.4 on 2025-03-13 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_remove_medicinelog_date_medicinelog_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelog',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
