# Generated by Django 5.1.4 on 2025-03-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_alter_medicinelog_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinelog',
            name='status',
        ),
    ]
