# Generated by Django 5.1.4 on 2025-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0007_remove_medicinelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelog',
            name='status',
            field=models.JSONField(default=dict),
        ),
    ]
