# Generated by Django 5.1.4 on 2025-03-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0008_medicinelog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinelog',
            name='status',
        ),
    ]
