# Generated by Django 5.1.4 on 2025-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0010_medicinestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
