# Generated by Django 5.1.4 on 2025-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0011_alter_medicinestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestatus',
            name='status',
            field=models.CharField(choices=[('taken', 'Taken'), ('missed', 'Missed')], default='missed', max_length=20),
        ),
    ]
